"""
List of constants
"""
AB_TESTS_SHEET_ID = "1yhqjAVuo_nlByP4G6zGfQ3gF3fz3IR4FXnqaN93OVUo"
AB_TESTS_LIVE = "AB - Tests Live"
AB_TESTS_PROD_SUPPORT = "AB - Prod Support"
INVALID_DAY_ENTERED = "Invalid day entered.  Make sure you entered an integer"
INVALID_EFEAT_ENTERED = "Invalid EFEAT# entered.  Please make sure the EFEAT# is 4 digits long."
INVALID_QUERY_ENTERED = "Invalid query entered."
JIRA_LINK = "https://contegixapp1.livenation.com/jira/browse/"
MAX_DAYS = "Max days is 120.  Please enter a number less than 120."
NO_RESULTS_FOUND = "No results found"
